platform :ios, '18.2'

project 'iosApp.xcodeproj'

target 'iosApp' do
  use_frameworks!

  pod 'mokoSocketIo', :git => 'https://github.com/icerockdev/moko-socket-io.git', :tag => 'release/0.6.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '18.2'
      config.build_settings.delete('VALID_ARCHS')
    end
  end
end
